# Generated by Django 4.2.13 on 2024-05-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_alter_books_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
