# Generated by Django 4.2.13 on 2024-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('pub', 'published'), ('drf', 'draft')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
